// <auto-generated />
using System;
using CSAKEFTPC4Core3;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CSAKEFTPC4Core3.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20200605101950_migration.1.20200605.10")]
    partial class migration12020060510
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CSARMetaPlan.Class.RAMetaObjektum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Leiras")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Megnevezes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nevter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublikusKod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Serialization")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RAMetaObjektums");

                    b.HasDiscriminator<string>("Discriminator").HasValue("RAMetaObjektum");
                });

            modelBuilder.Entity("CSEFTPC4Core3Objects.Ac4yObjects.Ac4yIdentificationBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("humanId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("publicHumanId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Ac4yIdentificationBase");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Ac4yIdentificationBase");
                });

            modelBuilder.Entity("CSEFTPC4Core3Objects.Ac4yObjects.Ac4yPersistentChild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Ac4yIdentificationId")
                        .HasColumnType("int");

                    b.Property<string>("GUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ages")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Ac4yIdentificationId");

                    b.ToTable("Ac4yPersistentChilds");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.AdatElem", b =>
                {
                    b.HasBaseType("CSARMetaPlan.Class.RAMetaObjektum");

                    b.Property<int?>("AdatkorId")
                        .HasColumnType("int");

                    b.Property<string>("Adattipus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BelsoNev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HumanNev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Irany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Opcionalis")
                        .HasColumnType("bit");

                    b.HasIndex("AdatkorId");

                    b.HasDiscriminator().HasValue("AdatElem");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.Adatkor", b =>
                {
                    b.HasBaseType("CSARMetaPlan.Class.RAMetaObjektum");

                    b.HasDiscriminator().HasValue("Adatkor");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.Ellenorzes", b =>
                {
                    b.HasBaseType("CSARMetaPlan.Class.RAMetaObjektum");

                    b.Property<string>("Feltetel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KepernyoId")
                        .HasColumnType("int");

                    b.Property<string>("Uzenet")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("KepernyoId");

                    b.HasDiscriminator().HasValue("Ellenorzes");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.Feladat", b =>
                {
                    b.HasBaseType("CSARMetaPlan.Class.RAMetaObjektum");

                    b.Property<string>("Azonosito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EllenorzesFolyamatban")
                        .HasColumnType("bit");

                    b.Property<string>("Ellenorzo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FeladatId")
                        .HasColumnType("int");

                    b.Property<bool>("Hibas")
                        .HasColumnType("bit");

                    b.Property<bool>("Hibatlan")
                        .HasColumnType("bit");

                    b.Property<bool>("JavitasFolyamatban")
                        .HasColumnType("bit");

                    b.Property<bool>("JavitasKesz")
                        .HasColumnType("bit");

                    b.Property<int?>("KepernyoId")
                        .HasColumnName("Feladat_KepernyoId")
                        .HasColumnType("int");

                    b.Property<int>("KeszultsegiSzazalek")
                        .HasColumnType("int");

                    b.Property<bool>("MegvalositasFolyamatban")
                        .HasColumnType("bit");

                    b.Property<bool>("MegvalositasKesz")
                        .HasColumnType("bit");

                    b.Property<string>("Megvalosito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipus")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("FeladatId");

                    b.HasIndex("KepernyoId");

                    b.HasDiscriminator().HasValue("Feladat");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.Funkcio", b =>
                {
                    b.HasBaseType("CSARMetaPlan.Class.RAMetaObjektum");

                    b.Property<string>("Billentyu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EgyediBeepites")
                        .HasColumnType("bit");

                    b.Property<string>("Engedely")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErintettObjektum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FejlecElem")
                        .HasColumnType("bit");

                    b.Property<string>("Feltetel")
                        .HasColumnName("Funkcio_Feltetel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GombsorElem")
                        .HasColumnType("bit");

                    b.Property<int?>("KepernyoId")
                        .HasColumnName("Funkcio_KepernyoId")
                        .HasColumnType("int");

                    b.Property<bool>("KepernyoKapcsolat")
                        .HasColumnType("bit");

                    b.Property<bool>("NemHasznalt")
                        .HasColumnType("bit");

                    b.Property<bool>("OsMetodus")
                        .HasColumnType("bit");

                    b.Property<string>("Szerep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Utasitas")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("KepernyoId");

                    b.HasDiscriminator().HasValue("Funkcio");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.Kepernyo", b =>
                {
                    b.HasBaseType("CSARMetaPlan.Class.RAMetaObjektum");

                    b.Property<string>("FoAzonosito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GyermekListaKepernyo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KepernyoId")
                        .HasColumnName("KepernyoId1")
                        .HasColumnType("int");

                    b.Property<string>("RegiKepernyo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UjKepernyo")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("KepernyoId");

                    b.HasDiscriminator().HasValue("Kepernyo");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.MegfeleltetesCsomopont", b =>
                {
                    b.HasBaseType("CSARMetaPlan.Class.RAMetaObjektum");

                    b.Property<int?>("CelMuveletId")
                        .HasColumnType("int");

                    b.HasIndex("CelMuveletId");

                    b.HasDiscriminator().HasValue("MegfeleltetesCsomopont");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.MegfeleltetesElem", b =>
                {
                    b.HasBaseType("CSARMetaPlan.Class.RAMetaObjektum");

                    b.Property<int?>("CelId")
                        .HasColumnType("int");

                    b.Property<int?>("ForrasId")
                        .HasColumnType("int");

                    b.Property<int?>("MegfeleltetesCsomopontId")
                        .HasColumnType("int");

                    b.HasIndex("CelId");

                    b.HasIndex("ForrasId");

                    b.HasIndex("MegfeleltetesCsomopontId");

                    b.HasDiscriminator().HasValue("MegfeleltetesElem");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.Metodus", b =>
                {
                    b.HasBaseType("CSARMetaPlan.Class.RAMetaObjektum");

                    b.Property<int?>("KepernyoId")
                        .HasColumnName("Metodus_KepernyoId")
                        .HasColumnType("int");

                    b.Property<bool>("Skalar")
                        .HasColumnType("bit");

                    b.Property<string>("Szerep")
                        .HasColumnName("Metodus_Szerep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Uzemmod")
                        .HasColumnType("int");

                    b.HasIndex("KepernyoId");

                    b.HasDiscriminator().HasValue("Metodus");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.Muvelet", b =>
                {
                    b.HasBaseType("CSARMetaPlan.Class.RAMetaObjektum");

                    b.Property<string>("FoAzonosito")
                        .HasColumnName("Muvelet_FoAzonosito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Foazonositos")
                        .HasColumnType("bit");

                    b.Property<int?>("KeresId")
                        .HasColumnType("int");

                    b.Property<int?>("MuveletId")
                        .HasColumnType("int");

                    b.Property<bool>("Nevproblemas")
                        .HasColumnType("bit");

                    b.Property<int>("TurelmiIdo")
                        .HasColumnType("int");

                    b.Property<int?>("ValaszId")
                        .HasColumnType("int");

                    b.Property<int>("ValaszTipus")
                        .HasColumnType("int");

                    b.HasIndex("KeresId");

                    b.HasIndex("MuveletId");

                    b.HasIndex("ValaszId");

                    b.HasDiscriminator().HasValue("Muvelet");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.Programkod", b =>
                {
                    b.HasBaseType("CSARMetaPlan.Class.RAMetaObjektum");

                    b.Property<string>("Forrasszoveg")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Programkod");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.Tabla", b =>
                {
                    b.HasBaseType("CSARMetaPlan.Class.RAMetaObjektum");

                    b.HasDiscriminator().HasValue("Tabla");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.TablaOszlop", b =>
                {
                    b.HasBaseType("CSARMetaPlan.Class.RAMetaObjektum");

                    b.Property<string>("Adattipus")
                        .HasColumnName("TablaOszlop_Adattipus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TablaId")
                        .HasColumnType("int");

                    b.HasIndex("TablaId");

                    b.HasDiscriminator().HasValue("TablaOszlop");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.TaroltEljarasArgumentum", b =>
                {
                    b.HasBaseType("CSARMetaPlan.Class.RAMetaObjektum");

                    b.Property<string>("Adattipus")
                        .HasColumnName("TaroltEljarasArgumentum_Adattipus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BelsoNev")
                        .HasColumnName("TaroltEljarasArgumentum_BelsoNev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HumanNev")
                        .HasColumnName("TaroltEljarasArgumentum_HumanNev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Irany")
                        .HasColumnName("TaroltEljarasArgumentum_Irany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MetodusId")
                        .HasColumnType("int");

                    b.Property<int?>("MuveletId")
                        .HasColumnName("TaroltEljarasArgumentum_MuveletId")
                        .HasColumnType("int");

                    b.Property<bool>("Opcionalis")
                        .HasColumnName("TaroltEljarasArgumentum_Opcionalis")
                        .HasColumnType("bit");

                    b.HasIndex("MetodusId");

                    b.HasIndex("MuveletId");

                    b.HasDiscriminator().HasValue("TaroltEljarasArgumentum");
                });

            modelBuilder.Entity("CSEFTPC4Core3Objects.Ac4yObjects.Ac4yIdentification", b =>
                {
                    b.HasBaseType("CSEFTPC4Core3Objects.Ac4yObjects.Ac4yIdentificationBase");

                    b.Property<int?>("ac4yIdentificationBaseId")
                        .HasColumnType("int");

                    b.HasIndex("ac4yIdentificationBaseId");

                    b.HasDiscriminator().HasValue("Ac4yIdentification");
                });

            modelBuilder.Entity("CSEFTPC4Core3Objects.Ac4yObjects.Ac4yPersistentChild", b =>
                {
                    b.HasOne("CSEFTPC4Core3Objects.Ac4yObjects.Ac4yIdentification", "Ac4yIdentification")
                        .WithMany()
                        .HasForeignKey("Ac4yIdentificationId");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.AdatElem", b =>
                {
                    b.HasOne("CSARMetaPlan.Class.Adatkor", null)
                        .WithMany("AdatElemLista")
                        .HasForeignKey("AdatkorId");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.Ellenorzes", b =>
                {
                    b.HasOne("CSARMetaPlan.Class.Kepernyo", null)
                        .WithMany("EllenorzesLista")
                        .HasForeignKey("KepernyoId");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.Feladat", b =>
                {
                    b.HasOne("CSARMetaPlan.Class.Feladat", null)
                        .WithMany("FeladatLista")
                        .HasForeignKey("FeladatId");

                    b.HasOne("CSARMetaPlan.Class.Kepernyo", null)
                        .WithMany("FeladatLista")
                        .HasForeignKey("KepernyoId");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.Funkcio", b =>
                {
                    b.HasOne("CSARMetaPlan.Class.Kepernyo", null)
                        .WithMany("FunkcioLista")
                        .HasForeignKey("KepernyoId");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.Kepernyo", b =>
                {
                    b.HasOne("CSARMetaPlan.Class.Kepernyo", null)
                        .WithMany("KepernyoLista")
                        .HasForeignKey("KepernyoId");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.MegfeleltetesCsomopont", b =>
                {
                    b.HasOne("CSARMetaPlan.Class.Muvelet", "CelMuvelet")
                        .WithMany("MegfeleltetesCsomopontLista")
                        .HasForeignKey("CelMuveletId");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.MegfeleltetesElem", b =>
                {
                    b.HasOne("CSARMetaPlan.Class.RAMetaObjektum", "Cel")
                        .WithMany()
                        .HasForeignKey("CelId");

                    b.HasOne("CSARMetaPlan.Class.RAMetaObjektum", "Forras")
                        .WithMany()
                        .HasForeignKey("ForrasId");

                    b.HasOne("CSARMetaPlan.Class.MegfeleltetesCsomopont", null)
                        .WithMany("MegfeleltetesElemLista")
                        .HasForeignKey("MegfeleltetesCsomopontId");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.Metodus", b =>
                {
                    b.HasOne("CSARMetaPlan.Class.Kepernyo", null)
                        .WithMany("MetodusLista")
                        .HasForeignKey("KepernyoId");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.Muvelet", b =>
                {
                    b.HasOne("CSARMetaPlan.Class.Adatkor", "Keres")
                        .WithMany()
                        .HasForeignKey("KeresId");

                    b.HasOne("CSARMetaPlan.Class.Muvelet", null)
                        .WithMany("MegfeleltetesLista")
                        .HasForeignKey("MuveletId");

                    b.HasOne("CSARMetaPlan.Class.Adatkor", "Valasz")
                        .WithMany()
                        .HasForeignKey("ValaszId");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.TablaOszlop", b =>
                {
                    b.HasOne("CSARMetaPlan.Class.Tabla", null)
                        .WithMany("TablaOszlopLista")
                        .HasForeignKey("TablaId");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.TaroltEljarasArgumentum", b =>
                {
                    b.HasOne("CSARMetaPlan.Class.Metodus", null)
                        .WithMany("ArgumentumLista")
                        .HasForeignKey("MetodusId");

                    b.HasOne("CSARMetaPlan.Class.Muvelet", null)
                        .WithMany("ArgumentumLista")
                        .HasForeignKey("MuveletId");
                });

            modelBuilder.Entity("CSEFTPC4Core3Objects.Ac4yObjects.Ac4yIdentification", b =>
                {
                    b.HasOne("CSEFTPC4Core3Objects.Ac4yObjects.Ac4yIdentificationBase", "ac4yIdentificationBase")
                        .WithMany()
                        .HasForeignKey("ac4yIdentificationBaseId");
                });
#pragma warning restore 612, 618
        }
    }
}
