// <auto-generated />
using System;
using CSAKEFTPC4Core3;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CSAKEFTPC4Core3.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20200605095531_migration.1.20200605.9")]
    partial class migration1202006059
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CSARMetaPlan.Class.AdatElem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adattipus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BelsoNev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HumanNev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Irany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Leiras")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Megnevezes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nevter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Opcionalis")
                        .HasColumnType("bit");

                    b.Property<string>("PublikusKod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Serialization")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdatElems");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.Ellenorzes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Feltetel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KepernyoId")
                        .HasColumnType("int");

                    b.Property<string>("Kod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Leiras")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Megnevezes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nevter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublikusKod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Serialization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uzenet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KepernyoId");

                    b.ToTable("Ellenorzes");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.Feladat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Azonosito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EllenorzesFolyamatban")
                        .HasColumnType("bit");

                    b.Property<string>("Ellenorzo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FeladatId")
                        .HasColumnType("int");

                    b.Property<string>("GUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Hibas")
                        .HasColumnType("bit");

                    b.Property<bool>("Hibatlan")
                        .HasColumnType("bit");

                    b.Property<bool>("JavitasFolyamatban")
                        .HasColumnType("bit");

                    b.Property<bool>("JavitasKesz")
                        .HasColumnType("bit");

                    b.Property<int?>("KepernyoId")
                        .HasColumnType("int");

                    b.Property<int>("KeszultsegiSzazalek")
                        .HasColumnType("int");

                    b.Property<string>("Kod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Leiras")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Megnevezes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MegvalositasFolyamatban")
                        .HasColumnType("bit");

                    b.Property<bool>("MegvalositasKesz")
                        .HasColumnType("bit");

                    b.Property<string>("Megvalosito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nevter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublikusKod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Serialization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FeladatId");

                    b.HasIndex("KepernyoId");

                    b.ToTable("Feladat");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.Funkcio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Billentyu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EgyediBeepites")
                        .HasColumnType("bit");

                    b.Property<string>("Engedely")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErintettObjektum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FejlecElem")
                        .HasColumnType("bit");

                    b.Property<string>("Feltetel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GombsorElem")
                        .HasColumnType("bit");

                    b.Property<int?>("KepernyoId")
                        .HasColumnType("int");

                    b.Property<bool>("KepernyoKapcsolat")
                        .HasColumnType("bit");

                    b.Property<string>("Kod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Leiras")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Megnevezes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NemHasznalt")
                        .HasColumnType("bit");

                    b.Property<string>("Nev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nevter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OsMetodus")
                        .HasColumnType("bit");

                    b.Property<string>("PublikusKod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Serialization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Szerep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Utasitas")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KepernyoId");

                    b.ToTable("Funkcio");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.Kepernyo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FoAzonosito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GyermekListaKepernyo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KepernyoId")
                        .HasColumnType("int");

                    b.Property<string>("Kod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Leiras")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Megnevezes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nevter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublikusKod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegiKepernyo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Serialization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UjKepernyo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KepernyoId");

                    b.ToTable("Keprnyos");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.Metodus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KepernyoId")
                        .HasColumnType("int");

                    b.Property<string>("Kod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Leiras")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Megnevezes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nevter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublikusKod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Serialization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Skalar")
                        .HasColumnType("bit");

                    b.Property<string>("Szerep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Uzemmod")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KepernyoId");

                    b.ToTable("Metodus");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.Programkod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Forrasszoveg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Leiras")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Megnevezes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nevter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublikusKod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Serialization")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Programkods");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.Tabla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Leiras")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Megnevezes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nevter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublikusKod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Serialization")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tablas");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.TablaOszlop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adattipus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Leiras")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Megnevezes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nevter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublikusKod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Serialization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TablaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TablaId");

                    b.ToTable("TablaOszlop");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.TaroltEljarasArgumentum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adattipus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BelsoNev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HumanNev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Irany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Leiras")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Megnevezes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MetodusId")
                        .HasColumnType("int");

                    b.Property<string>("Nev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nevter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Opcionalis")
                        .HasColumnType("bit");

                    b.Property<string>("PublikusKod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Serialization")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MetodusId");

                    b.ToTable("TaroltEljarasArgumentum");
                });

            modelBuilder.Entity("CSEFTPC4Core3Objects.Ac4yObjects.Ac4yIdentificationBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("humanId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("publicHumanId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Ac4yIdentificationBase");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Ac4yIdentificationBase");
                });

            modelBuilder.Entity("CSEFTPC4Core3Objects.Ac4yObjects.Ac4yPersistentChild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Ac4yIdentificationId")
                        .HasColumnType("int");

                    b.Property<string>("GUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ages")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Ac4yIdentificationId");

                    b.ToTable("Ac4yPersistentChilds");
                });

            modelBuilder.Entity("CSEFTPC4Core3Objects.Ac4yObjects.Ac4yIdentification", b =>
                {
                    b.HasBaseType("CSEFTPC4Core3Objects.Ac4yObjects.Ac4yIdentificationBase");

                    b.Property<int?>("ac4yIdentificationBaseId")
                        .HasColumnType("int");

                    b.HasIndex("ac4yIdentificationBaseId");

                    b.HasDiscriminator().HasValue("Ac4yIdentification");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.Ellenorzes", b =>
                {
                    b.HasOne("CSARMetaPlan.Class.Kepernyo", null)
                        .WithMany("EllenorzesLista")
                        .HasForeignKey("KepernyoId");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.Feladat", b =>
                {
                    b.HasOne("CSARMetaPlan.Class.Feladat", null)
                        .WithMany("FeladatLista")
                        .HasForeignKey("FeladatId");

                    b.HasOne("CSARMetaPlan.Class.Kepernyo", null)
                        .WithMany("FeladatLista")
                        .HasForeignKey("KepernyoId");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.Funkcio", b =>
                {
                    b.HasOne("CSARMetaPlan.Class.Kepernyo", null)
                        .WithMany("FunkcioLista")
                        .HasForeignKey("KepernyoId");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.Kepernyo", b =>
                {
                    b.HasOne("CSARMetaPlan.Class.Kepernyo", null)
                        .WithMany("KepernyoLista")
                        .HasForeignKey("KepernyoId");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.Metodus", b =>
                {
                    b.HasOne("CSARMetaPlan.Class.Kepernyo", null)
                        .WithMany("MetodusLista")
                        .HasForeignKey("KepernyoId");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.TablaOszlop", b =>
                {
                    b.HasOne("CSARMetaPlan.Class.Tabla", null)
                        .WithMany("TablaOszlopLista")
                        .HasForeignKey("TablaId");
                });

            modelBuilder.Entity("CSARMetaPlan.Class.TaroltEljarasArgumentum", b =>
                {
                    b.HasOne("CSARMetaPlan.Class.Metodus", null)
                        .WithMany("ArgumentumLista")
                        .HasForeignKey("MetodusId");
                });

            modelBuilder.Entity("CSEFTPC4Core3Objects.Ac4yObjects.Ac4yPersistentChild", b =>
                {
                    b.HasOne("CSEFTPC4Core3Objects.Ac4yObjects.Ac4yIdentification", "Ac4yIdentification")
                        .WithMany()
                        .HasForeignKey("Ac4yIdentificationId");
                });

            modelBuilder.Entity("CSEFTPC4Core3Objects.Ac4yObjects.Ac4yIdentification", b =>
                {
                    b.HasOne("CSEFTPC4Core3Objects.Ac4yObjects.Ac4yIdentificationBase", "ac4yIdentificationBase")
                        .WithMany()
                        .HasForeignKey("ac4yIdentificationBaseId");
                });
#pragma warning restore 612, 618
        }
    }
}
